name:                knotesAPI
version:             0.1.0.0
github:              "nuclearpinguin/knotes"
license:             BSD3
author:              "Tomek Urbaszek"
maintainer:          "t@bitreport.org"
copyright:           "2019 Tomek Urbaszek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nuclearpinguin/knotes#readme>

dependencies:
- base
- aeson
- Spock
- text
- http-types
- wai-extra
- monad-logger
- persistent
# - pg_config
# - persistent-postgresql
- persistent-sqlite
- persistent-template
- unordered-containers
- bytestring
- parsec

library:
  source-dirs: src

executables:
  knotesAPI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knotesAPI

tests:
  knotesAPI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knotesAPI
